name: import admin openapi
on:
  repository_dispatch:
    types: [openapi-updated]
  workflow_dispatch:

jobs:
  import-admin-openapi:
    name: import-admin-openapi
    runs-on: ubuntu-latest
    timeout-minutes: 25
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: getsentry/action-github-app-token@v2
        id: get-token
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE }}

      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: ummm/a
          path: a
          token: ${{ steps.get-token.outputs.token }}

      - name: import admin openapi
        run: |
          cp a/config/openapi/admin/bundle.yaml openapi.yaml
          rm -rf a

      - name: create pullrequest
        uses: peter-evans/create-pull-request@v5
        with:
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          reviewers: ${{ github.event.client_payload.author }}
          commit-message: import openapi.yaml from ummm/a
          branch: import-admin-openapi
          branch-suffix: timestamp
          delete-branch: true
          title: 'admin openapi.yaml updated.'
          body: |
            admin openapi.yaml updated.
